### PR TITLE
Add type traits for search structures

### PR DESCRIPTION
**Pull request by jlumpe**
Added two type trait functions for search structure types, `datatype` and `distancetype`. These can be useful for pre-allocating arrays, for example.

### CODE REVIEW

**Comment by Datseris** [comment]
Oh WOW! I never expected that someone else would use this, much less so actually contribute!!! Thank you so much! Is this good to go from your end?

**Comment by jlumpe** [comment]
It should be good, there are a few basic tests for `KDTree` with it. There are a couple of things I wasn't sure about:

* Neither function is exported. They probably won't be needed in basic usage so I think this makes sense.
* I didn't add anything about them to the dev section of the docs yet.

I definitely prefer the API in this package to `NearestNeighbors`, their requirement that data points must be (uniformly-sized) arrays doesn't work for my purposes. It's also really useful to have the skip predicate function.

I was working on adding the skip functionality to `VPTrees` and thought I might as well try to bring it under this API while I'm at it, if you think that would be useful.

**Comment by Datseris** [comment]
> I was working on adding the skip functionality to VPTrees and thought I might as well try to bring it under this API while I'm at it, if you think that would be useful.

Yes, please do! Any contribution of more packages under this API is very welcome!

The original plan was for this package to only provide the API, and not actually implement it for packages, and instead the implementation to be at the specific packages. Alas, this didn't happen in the end, so I made the decision to just add the packages here as dependencies. I mean, it isn't that bad with the new package manager. So yes, if you want to extend VPTrees please go ahead!


> I didn't add anything about them to the dev section of the docs yet.

If you are willing to add a few words to the dev docs, I think it is a good idea!

**Comment by jlumpe** [comment]
Ok, I've thought about this a bit more and I think this should be modified a bit.

My use case - I wanted to write tests for my additions to `VPTrees`, but realized that these tests are universal and it would be useful to put them in functions in a submodule of `Neighbors` so that they could be used for other search structure types. One of these is comparing search results to a brute force search, so I was writing brute force search functions. These require I pre-allocate an array to store distance values.

So basically, given values for `metric`, `data`, and `query`, I need a way to know the type of `metric(query, data[i])`. There are a few possibilities for this:
1. Just use `Float64`. Should work in pretty much all cases, but some metrics may return e.g. `Float32` for performance reasons and ideally that should be preserved.
2. Have the creator/owner of the metric add a method to a function `distancetype(::MyMetric, ::Type{DataType})`. This is what I did in this PR but using the search structure instead of the metric directly.
3. Just call `metric(query, data[1])` and get the return type. Inelegant but works.
4. Other Julia type inference magic techniques.

I think I found a better way to do this using a combination of #s 3 and 4, so there's not really a need to add `distancetype` to the public API at the moment. I removed that and add a `getmetric(searchstructure)` function, which I think could be useful.

Since neither of the functions introduced in this PR are used for anything yet I haven't written anything about them in the dev docs.

**Comment by Datseris** [comment]
Slack gave me `Base.return_types` or `Core.Compiler.return_type`, does this help to not call anything? (i.e. do `4`)

**Comment by Datseris** [comment]
Hm then again someone says it is not recommended to use these internal functions, so better just do step 3 instead...

**Comment by jlumpe** [comment]
Here's what I've written:

```julia
"""
	metricreturntype(metric, x, y=x)

Get the expected return type of `metric(x, y)`. This is inferred statically if
possible, otherwise the function is actually called with the supplied arguments.
Always returns a concrete type.
"""
function metricreturntype(metric, x, y=x)
	# The following should return a concrete type if metric is type stable:
	T = Core.Compiler.return_type(metric, (typeof(x), typeof(y)))
	T isa DataType && T.isconcretetype && return T
	return typeof(metric(x, y))
end
```

I *think* this should work in more or less all cases.

**Comment by Datseris** [comment]
yeap seems good to me!

**Comment by jlumpe** [comment]
After spending most of the last 5 hours struggling with this and delving into the `Base` source code, I finally figured out I have to replace

```julia
Core.Compiler.return_type(metric, (typeof(x), typeof(y)))
```

with

```julia
Core.Compiler.return_type(metric, Tuple{typeof(x), typeof(y)})
```

in order for the result of the function to be inferable. I'll submit it in another PR.

**Comment by Datseris** [comment]
alright, then I'll merge this

**Pull request merged**
