### PR TITLE
Brute force searches

### PR DESCRIPTION
**Pull request by jlumpe**

### CODE REVIEW

**Comment by Datseris** [comment]
Wow, really big, really good. I think this warrants a minor version change in project.toml , 0.1 -> 0.2

**Comment by jlumpe** [comment]
Previous implementation of `search(..., ::NeighborNumber)` was a case of premature optimization, changed to a less efficient but much simpler implementation that avoids the dependence on `DataStructures`.

**Comment by jlumpe** [comment]
Question - should `bruteforcesearch`/`BruteForceSearch` be exported?

**Comment by Datseris** [comment]
I think the only thing that should be exported is `BruteForceSearch`. After all it is a "search structure" that satisfies all API of Neighborhood.jl, so why not? 

May I suggest to rename it to just `BruteForce` by the way?

**Comment by jlumpe** [comment]
Done, should be good to merge.

**Comment by Datseris** [comment]
@jlumpe Sorry to annoy you, but I recall at some point you said you have extended the interface also for VPTrees? If so, perhaps we can put it here as well?

**Pull request merged**
